(function(){'use strict';
const state=cdnaLoadState();let current=0,answers=[];const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const pages={home:$('#page-home'),how:$('#page-how'),careers:$('#page-careers'),assessment:$('#page-assessment'),analysis:$('#page-analysis'),results:$('#page-results')};
function route(){let r=location.hash.replace('#','')||'home';if(r==='results'&&!state.lastResult)r='home';if(!pages[r])r='home';Object.entries(pages).forEach(([k,e])=>e.classList.toggle('active',k===r));window.scrollTo(0,0);if(r==='assessment')renderQuestion();if(r==='careers')renderExplorer();if(r==='results'&&state.lastResult)renderResults(state.lastResult)}
window.addEventListener('hashchange',route);$('#menu-btn').addEventListener('click',()=>$('#nav-links').classList.toggle('open'));$$('#nav-links a').forEach(a=>a.addEventListener('click',()=>$('#nav-links').classList.remove('open')));$$('[data-start]').forEach(b=>b.addEventListener('click',startAssessment));
function startAssessment(){answers=[];current=0;location.hash='assessment';renderQuestion()}
function renderQuestion(){const q=CDNA_QUESTIONS[current];$('#q-counter').textContent=String(current+1).padStart(2,'0')+' / 20';$('#progress-fill').style.width=((current+1)/20*100)+'%';$('#q-text').textContent=q.text;$('#back-btn').disabled=current===0;const existing=answers.find(x=>x.questionId===q.id);const wrap=$('#q-answers');wrap.innerHTML='';q.answers.forEach((a,i)=>{const b=document.createElement('button');b.className='answer'+(existing?.answerId===a.id?' selected':'');b.innerHTML=`<span class="letter mono">${String.fromCharCode(65+i)}</span><h3>${a.title}</h3><p>${a.desc}</p>`;b.onclick=()=>choose(q,a);wrap.appendChild(b)});$('#answer-state').textContent=existing?'Answer saved — you can change it.':'Choose the answer that feels most like you.'}
function choose(q,a){const idx=answers.findIndex(x=>x.questionId===q.id);const rec={questionId:q.id,answerId:a.id};if(idx>=0)answers[idx]=rec;else answers.push(rec);$('#nova-text').textContent=a.nova||['Interesting signal.','Pattern updated.','That choice reveals something.','Your profile is taking shape.'][current%4];if(current<19){setTimeout(()=>{current++;renderQuestion()},220)}else{setTimeout(runAnalysis,250)}}
$('#back-btn').onclick=()=>{if(current>0){current--;renderQuestion()}};
function runAnalysis(){location.hash='analysis';const lines=['Reading reasoning patterns…','Mapping interests and motivation…','Analyzing work style…','Comparing 600+ careers…','Building your profile…'];const ul=$('#analysis-lines');ul.innerHTML='';lines.forEach(x=>{const li=document.createElement('li');li.textContent=x;ul.appendChild(li)});let i=0;const timer=setInterval(()=>{if(i>0)ul.children[i-1].classList.add('on');if(i<ul.children.length)i++;else{clearInterval(timer);setTimeout(finish,350)}},260)}
function finish(){const raw=cdnaAccumulateProfile(answers,CDNA_QUESTIONS);const profile=cdnaNormalizeProfile(raw);const top=cdnaMatchCareers(profile,10);const result={answers:[...answers],profile,topCareers:top.map(c=>({id:c.id,name:c.name,domain:c.domain,compatibility:c.compatibility,strongest:c.strongest,development:c.development})),timestamp:new Date().toISOString()};cdnaCommitResult(state,result);location.hash='results'}
function renderResults(result){if(!result?.profile)return;const p=result.profile;renderTraitBars(p);renderRadar(p);renderDomains(p);renderTop10(result.topCareers);renderActivities(result.topCareers);renderHistory()}
function renderTraitBars(p){const el=$('#trait-bars');el.innerHTML='';cdnaTopTraitNames(p,8).forEach(t=>{el.innerHTML+=`<div class="trait-row"><div class="trait-label"><span>${t.name}</span><b>${t.value}</b></div><div class="bar"><i style="width:${t.value}%"></i></div></div>`})}
function renderRadar(p){const c=$('#radar'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||600,h=c.clientHeight||420;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const traits=cdnaTopTraitNames(p,7),cx=w/2,cy=h/2,r=Math.min(w,h)*.32;ctx.font='11px Inter';ctx.textAlign='center';for(let ring=1;ring<=4;ring++){ctx.beginPath();for(let i=0;i<traits.length;i++){const a=-Math.PI/2+i*2*Math.PI/traits.length,rr=r*ring/4,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle='rgba(41,40,36,.12)';ctx.stroke()}ctx.beginPath();traits.forEach((t,i)=>{const a=-Math.PI/2+i*2*Math.PI/traits.length,rr=r*t.value/100,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='rgba(31,90,67,.15)';ctx.fill();ctx.strokeStyle='#1f5a43';ctx.stroke();traits.forEach((t,i)=>{const a=-Math.PI/2+i*2*Math.PI/traits.length,x=cx+Math.cos(a)*(r+30),y=cy+Math.sin(a)*(r+30);ctx.fillStyle='#5f5a52';ctx.fillText(t.name.split(' ')[0],x,y)})}
function renderDomains(p){const el=$('#domain-bars');el.innerHTML='';cdnaDomainDistribution(p).slice(0,7).forEach(([d,v])=>{el.innerHTML+=`<div class="domain-row"><span>${d}</span><div class="bar"><i style="width:${v}%"></i></div><strong>${v}</strong></div>`})}
function openCareer(id){const c=CDNA_CAREER_CATALOG.find(x=>x.id===id);if(!c)return;$('#modal-domain').textContent=c.domain;$('#modal-name').textContent=c.name;$('#modal-description').textContent=c.description;$('#modal-skills').innerHTML=c.skills.map(x=>`<span class="pill">${x}</span>`).join('');$('#modal-style').textContent=c.workStyles.join(' · ');$('#modal-environment').textContent=c.environments.join(' · ');$('#modal-education').textContent=c.education;$('#modal-related').textContent=c.relatedCareers.join(' · ');$('#career-modal').hidden=false} $$('#career-modal [data-close-modal]').forEach(x=>x.addEventListener('click',()=>$('#career-modal').hidden=true));
function renderTop10(top){const el=$('#top10');el.innerHTML='';top.forEach((c,i)=>{const names=(c.strongest||[]).map(k=>k.replace(/[A-Z]/g,m=>' '+m).replace(/^./,m=>m.toUpperCase()));el.innerHTML+=`<article class="top-card"><div class="rank">${String(i+1).padStart(2,'0')}</div><span class="domain">${c.domain}</span><h3>${c.name}</h3><div class="compat">${c.compatibility}% PATTERN COMPATIBILITY</div><p class="why">Strong alignment across ${names.slice(0,3).join(', ')}. This is a potential path worth testing, not a prediction.</p><div class="signals">${names.slice(0,3).map(x=>`<span class="pill">${x}</span>`).join('')}</div><div class="dev">Potential development area: ${String(c.development||'domain experience').replace(/[A-Z]/g,m=>' '+m).replace(/^./,m=>m.toUpperCase())}</div><button class="secondary" style="margin-top:14px" data-top-career="${c.id}">Explore Career →</button></article>`});$$('#top10 [data-top-career]').forEach(b=>b.addEventListener('click',()=>openCareer(b.dataset.topCareer)))}
function renderActivities(top){const el=$('#activities');el.innerHTML=cdnaActivities(top.map(x=>CDNA_CAREER_CATALOG.find(c=>c.id===x.id)||x)).map(a=>`<article class="activity"><b>${a.domain}</b><h3>${a.text}</h3><p>A small, practical experiment connected to ${a.career}.</p></article>`).join('');const first=top[0];const roadmap=$('#roadmap');if(first){roadmap.classList.add('show');roadmap.innerHTML=`<h2>${first.name} exploration roadmap</h2><p>Use this sequence to test the path before making a long-term commitment.</p><div class="road-steps"><span>Explore the field</span><span>Learn fundamentals</span><span>Try a mini project</span><span>Research education paths</span><span>Talk to professionals</span><span>Review your evidence</span></div>`}}
function renderHistory(){const el=$('#history');el.innerHTML=`<h3>Assessment history</h3><p>${state.history.length?`${state.history.length} previous result${state.history.length>1?'s':''} saved locally.`:'This is your first completed assessment.'}</p>`}
function renderExplorer(){const filter=$('#domain-filter');if(!filter.dataset.ready){CDNA_DOMAIN_NAMES.sort().forEach(d=>filter.insertAdjacentHTML('beforeend',`<option>${d}</option>`));filter.dataset.ready='1';['input','change'].forEach(ev=>{$('#career-search').addEventListener(ev,renderExplorer);filter.addEventListener(ev,renderExplorer);$('#sort-careers').addEventListener(ev,renderExplorer)}); }const q=$('#career-search').value.toLowerCase();const d=filter.value;let list=CDNA_CAREER_CATALOG.filter(c=>(!q||(`${c.name} ${c.domain} ${c.description}`).toLowerCase().includes(q))&&(!d||c.domain===d));const sort=$('#sort-careers').value;list.sort((a,b)=>sort==='domain'?a.domain.localeCompare(b.domain)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));$('#explorer-count').textContent=`Showing ${list.length} of ${CDNA_CAREER_CATALOG.length} careers`;$('#career-grid').innerHTML=list.map(c=>`<article class="career-card" data-career-id="${c.id}"><span class="domain">${c.domain}</span><h3>${c.name}</h3><p>${c.description}</p><div class="pills">${c.skills.map(s=>`<span class="pill">${s}</span>`).join('')}</div><button class="secondary" style="margin-top:14px" data-career-id="${c.id}">Explore Career</button></article>`).join('')||'<div class="panel">No careers match that search.</div>'; $$('#career-grid [data-career-id]').forEach(b=>b.addEventListener('click',()=>openCareer(b.dataset.careerId)))}
$('#reset-btn').onclick=()=>{cdnaResetState();location.hash='home';location.reload()};
if(CDNA_CAREER_CATALOG.length<500)console.error('Career database must contain 500+ entries.');route();
})();
