const CDNA_DOMAIN_PROFILES = {
  'Technology':{traits:{logicalReasoning:.85,analysis:.8,technicalInterest:.95,innovation:.8,attentionToDetail:.75},interests:['technology','systems','building'],workStyles:['focused','project-based','iterative'],environments:['office','remote','lab'],motivation:['building','solving','innovation'],skills:['Systems thinking','Problem solving','Digital tools'],education:'Relevant degree, diploma, bootcamp or demonstrated portfolio depending on role.'},
  'Engineering':{traits:{logicalReasoning:.85,spatialReasoning:.8,practicalAbility:.85,analysis:.8,attentionToDetail:.85},interests:['engineering','design','systems'],workStyles:['project-based','technical','collaborative'],environments:['office','field','lab'],motivation:['building','solving','impact'],skills:['Technical analysis','Design','Problem solving'],education:'Usually a relevant engineering degree or accredited technical training.'},
  'Science & Research':{traits:{scientificThinking:.95,curiosity:.95,researchOrientation:.95,analysis:.85,patience:.8},interests:['science','research','discovery'],workStyles:['research','focused','methodical'],environments:['lab','university','field'],motivation:['discovery','learning','impact'],skills:['Research methods','Evidence analysis','Documentation'],education:'Usually undergraduate study followed by specialized training; research roles often require postgraduate study.'},
  'Healthcare & Medicine':{traits:{scientificThinking:.75,empathy:.9,helpingOrientation:.95,attentionToDetail:.9,communication:.8,patience:.85},interests:['health','people','science'],workStyles:['service','team-based','structured'],environments:['hospital','clinic','community'],motivation:['helping','impact','service'],skills:['Communication','Evidence-based practice','Care'],education:'Role-specific professional education, licensing and supervised training are common.'},
  'Finance & Economics':{traits:{numericalReasoning:.95,analysis:.9,businessOrientation:.9,attentionToDetail:.85,decisionMaking:.8},interests:['finance','markets','economics'],workStyles:['analytical','deadline-driven','structured'],environments:['office','remote','client-facing'],motivation:['impact','results','problem-solving'],skills:['Quantitative analysis','Financial reasoning','Communication'],education:'Relevant degree or professional qualification depending on role.'},
  'Business & Management':{traits:{leadership:.9,communication:.85,businessOrientation:.95,persuasion:.8,decisionMaking:.9,adaptability:.8},interests:['business','strategy','organizations'],workStyles:['collaborative','leadership','project-based'],environments:['office','client-facing','hybrid'],motivation:['results','leadership','impact'],skills:['Strategy','Communication','Decision making'],education:'Business, management or domain-specific education; experience is important.'},
  'Law & Legal Services':{traits:{verbalReasoning:.95,analysis:.9,attentionToDetail:.9,communication:.9,persuasion:.8,investigation:.8},interests:['law','policy','evidence'],workStyles:['research','client-facing','structured'],environments:['office','court','public service'],motivation:['justice','problem-solving','influence'],skills:['Legal research','Writing','Argumentation'],education:'Legal education and jurisdiction-specific qualification are typically required.'},
  'Education & Training':{traits:{communication:.9,empathy:.9,helpingOrientation:.95,patience:.9,organization:.8,verbalReasoning:.8},interests:['learning','people','teaching'],workStyles:['service','collaborative','structured'],environments:['school','university','community'],motivation:['helping','learning','impact'],skills:['Teaching','Communication','Planning'],education:'Relevant education/training credentials and role-specific certification may be required.'},
  'Psychology & Human Services':{traits:{empathy:.95,helpingOrientation:.95,communication:.85,curiosity:.85,investigation:.75,patience:.9},interests:['people','behavior','wellbeing'],workStyles:['service','research','client-facing'],environments:['clinic','community','office'],motivation:['helping','impact','understanding'],skills:['Listening','Assessment','Communication'],education:'Relevant degree and, for regulated roles, supervised professional qualification.'},
  'Design & Architecture':{traits:{creativity:.95,visualThinking:.95,spatialReasoning:.9,artisticExpression:.85,empathy:.75,attentionToDetail:.85},interests:['design','visuals','built environment'],workStyles:['creative','project-based','collaborative'],environments:['studio','office','field'],motivation:['creation','impact','craft'],skills:['Visual communication','Design process','Prototyping'],education:'Relevant design, architecture or portfolio-based training depending on role.'},
  'Media & Journalism':{traits:{verbalReasoning:.95,communication:.95,curiosity:.9,investigation:.85,persuasion:.75,adaptability:.8},interests:['media','storytelling','current affairs'],workStyles:['deadline-driven','creative','field'],environments:['studio','field','remote'],motivation:['storytelling','impact','discovery'],skills:['Writing','Research','Interviewing'],education:'Relevant communication, journalism or media training; portfolio experience is valuable.'},
  'Marketing & Sales':{traits:{communication:.95,persuasion:.95,businessOrientation:.9,socialInteraction:.9,creativity:.8,adaptability:.85},interests:['marketing','customers','growth'],workStyles:['client-facing','collaborative','fast-paced'],environments:['office','field','remote'],motivation:['results','influence','creation'],skills:['Communication','Market understanding','Presentation'],education:'Business, marketing or domain education plus practical experience.'},
  'Arts & Creative Practice':{traits:{artisticExpression:.98,creativity:.98,visualThinking:.85,innovation:.85,independence:.85},interests:['art','culture','expression'],workStyles:['creative','independent','project-based'],environments:['studio','stage','field'],motivation:['creation','expression','impact'],skills:['Craft','Creative direction','Portfolio development'],education:'Formal study can help, but portfolio, practice and body of work are often central.'},
  'Environment & Agriculture':{traits:{scientificThinking:.85,practicalAbility:.85,curiosity:.85,investigation:.8,patience:.8,spatialReasoning:.7},interests:['environment','nature','agriculture'],workStyles:['field','research','practical'],environments:['field','lab','community'],motivation:['impact','discovery','service'],skills:['Observation','Field methods','Data collection'],education:'Relevant science, agriculture, environmental or technical training depending on role.'},
  'Public Service & Government':{traits:{communication:.8,organization:.85,leadership:.8,helpingOrientation:.85,verbalReasoning:.8,decisionMaking:.8},interests:['public service','policy','communities'],workStyles:['structured','service','collaborative'],environments:['office','field','public service'],motivation:['service','impact','leadership'],skills:['Policy thinking','Communication','Administration'],education:'Role-specific public administration, law, policy or professional education.'},
  'Skilled Trades & Manufacturing':{traits:{practicalAbility:.98,attentionToDetail:.9,spatialReasoning:.85,patience:.8,logicalReasoning:.75},interests:['making','machines','craft'],workStyles:['hands-on','technical','structured'],environments:['workshop','factory','field'],motivation:['craft','building','problem-solving'],skills:['Technical craft','Safety','Troubleshooting'],education:'Apprenticeship, vocational training, certification or technical education depending on role.'},
  'Transportation & Aviation':{traits:{attentionToDetail:.9,decisionMaking:.9,practicalAbility:.8,adaptability:.8,communication:.75,spatialReasoning:.8},interests:['transport','navigation','operations'],workStyles:['procedural','field','team-based'],environments:['airport','field','vehicle'],motivation:['precision','service','operations'],skills:['Safety procedures','Navigation','Decision making'],education:'Role-specific licensing, certification and supervised training are common.'},
  'Hospitality & Tourism':{traits:{socialInteraction:.95,communication:.9,empathy:.85,adaptability:.9,organization:.8,persuasion:.65},interests:['travel','service','events'],workStyles:['client-facing','fast-paced','team-based'],environments:['hotel','travel','events'],motivation:['service','experience','people'],skills:['Guest service','Coordination','Communication'],education:'Hospitality/tourism education or practical training depending on role.'},
  'Sports & Fitness':{traits:{practicalAbility:.8,communication:.85,empathy:.8,leadership:.75,adaptability:.85,patience:.8},interests:['sport','fitness','performance'],workStyles:['hands-on','coaching','client-facing'],environments:['gym','field','clinic'],motivation:['performance','helping','leadership'],skills:['Coaching','Assessment','Communication'],education:'Sport science, coaching, fitness or role-specific certification depending on profession.'},
  'Social Sciences & Policy':{traits:{verbalReasoning:.9,analysis:.9,curiosity:.9,researchOrientation:.9,communication:.85,empathy:.75},interests:['society','policy','research'],workStyles:['research','writing','collaborative'],environments:['office','university','field'],motivation:['discovery','impact','understanding'],skills:['Research','Writing','Analysis'],education:'Relevant social science, policy or research education; postgraduate study is common in research roles.'}
};

const CDNA_CAREER_SETS = {
'Technology':['Software Developer','Web Developer','Frontend Developer','Backend Developer','Full Stack Developer','Mobile Application Developer','Game Developer','AR/VR Developer','AI Engineer','Machine Learning Engineer','Natural Language Processing Engineer','Computer Vision Engineer','Robotics Software Engineer','Data Engineer','Data Architect','Data Analyst','Data Scientist','Business Intelligence Analyst','Database Administrator','Cloud Engineer','Cloud Architect','DevOps Engineer','Site Reliability Engineer','Platform Engineer','Cybersecurity Analyst','Security Engineer','Penetration Tester','Digital Forensics Analyst','Security Architect','Incident Response Analyst','Network Engineer','Network Architect','Systems Administrator','Systems Architect','Solutions Architect','Technical Product Manager','Product Manager','QA Engineer','Test Automation Engineer','Release Engineer','Embedded Systems Developer','Firmware Engineer','Blockchain Developer','Cryptography Engineer','Developer Relations Engineer','Technical Writer','UX Engineer','Accessibility Specialist','IT Support Specialist','IT Project Manager','IT Auditor','Computer Systems Analyst','Information Architect','Search Engine Optimization Specialist'],
'Engineering':['Civil Engineer','Structural Engineer','Geotechnical Engineer','Transportation Engineer','Water Resources Engineer','Environmental Engineer','Mechanical Engineer','Aerospace Engineer','Automotive Engineer','Marine Engineer','Naval Architect','Chemical Engineer','Process Engineer','Industrial Engineer','Manufacturing Engineer','Materials Engineer','Metallurgical Engineer','Biomedical Engineer','Electrical Engineer','Electronics Engineer','Power Systems Engineer','Control Systems Engineer','Instrumentation Engineer','Telecommunications Engineer','Petroleum Engineer','Mining Engineer','Nuclear Engineer','Agricultural Engineer','Food Process Engineer','Fire Protection Engineer','Railway Engineer','Mechatronics Engineer','Renewable Energy Engineer','Solar Energy Engineer','Wind Energy Engineer','Acoustical Engineer','Optical Engineer','Photonics Engineer','Packaging Engineer','Safety Engineer','Reliability Engineer','Quality Engineer','Systems Engineer','Design Engineer','Production Engineer','Automation Engineer','Robotics Engineer','Facilities Engineer','Engineering Consultant','Engineering Project Manager'],
'Science & Research':['Biologist','Microbiologist','Molecular Biologist','Cell Biologist','Geneticist','Biochemist','Biophysicist','Chemist','Organic Chemist','Analytical Chemist','Materials Scientist','Physicist','Astrophysicist','Astronomer','Geologist','Geophysicist','Meteorologist','Climatologist','Oceanographer','Hydrologist','Ecologist','Marine Biologist','Botanist','Zoologist','Entomologist','Epidemiologist','Immunologist','Neuroscientist','Toxicologist','Pharmacologist','Forensic Scientist','Food Scientist','Soil Scientist','Atmospheric Scientist','Data Researcher','Operations Research Analyst','Research Scientist','Clinical Research Coordinator','Laboratory Scientist','Science Policy Analyst'],
'Healthcare & Medicine':['Physician','Surgeon','Anesthesiologist','Cardiologist','Dermatologist','Neurologist','Psychiatrist','Pediatrician','Radiologist','Pathologist','Oncologist','Emergency Medicine Physician','Family Medicine Physician','Internal Medicine Physician','Obstetrician-Gynecologist','Dentist','Orthodontist','Periodontist','Dental Hygienist','Pharmacist','Clinical Pharmacist','Registered Nurse','Nurse Practitioner','Nurse Anesthetist','Midwife','Paramedic','Emergency Medical Technician','Physician Assistant','Physical Therapist','Occupational Therapist','Speech-Language Pathologist','Respiratory Therapist','Radiologic Technologist','Medical Laboratory Scientist','Medical Sonographer','Dietitian','Nutritionist','Optometrist','Audiologist','Podiatrist','Chiropractor','Veterinarian','Veterinary Technician','Medical Coder','Health Information Technologist','Medical Records Specialist','Medical Physicist','Genetic Counselor','Public Health Specialist','Health Services Manager'],
'Finance & Economics':['Accountant','Auditor','Tax Accountant','Forensic Accountant','Financial Analyst','Investment Analyst','Portfolio Manager','Risk Analyst','Credit Analyst','Actuary','Economist','Financial Economist','Quantitative Analyst','Investment Banker','Commercial Banker','Loan Officer','Financial Planner','Wealth Manager','Treasury Analyst','Budget Analyst','Procurement Analyst','Cost Estimator','Insurance Underwriter','Claims Adjuster','Insurance Broker','Compliance Analyst','Financial Controller','Chief Financial Officer','Securities Trader','Market Research Analyst'],
'Business & Management':['Business Analyst','Management Consultant','Strategy Consultant','Operations Manager','Operations Analyst','Project Manager','Program Manager','Product Operations Manager','General Manager','Business Development Manager','Entrepreneur','Startup Founder','Supply Chain Manager','Logistics Manager','Procurement Manager','Purchasing Manager','Human Resources Manager','Talent Acquisition Specialist','Recruiter','Compensation Analyst','Training Manager','Organizational Development Specialist','Change Management Consultant','Customer Success Manager','Account Manager','Office Manager','Administrative Manager','Franchise Manager','Retail Manager','Category Manager'],
'Law & Legal Services':['Lawyer','Attorney','Solicitor','Barrister','Legal Advisor','Corporate Lawyer','Criminal Lawyer','Family Lawyer','Immigration Lawyer','Intellectual Property Lawyer','Tax Lawyer','Employment Lawyer','Environmental Lawyer','Human Rights Lawyer','Litigator','Legal Researcher','Paralegal','Legal Secretary','Legal Assistant','Compliance Officer','Contract Manager','Arbitrator','Mediator','Judge','Magistrate','Court Reporter','Court Clerk','Legal Operations Manager','Patent Agent','Legal Consultant'],
'Education & Training':['Teacher','Primary School Teacher','Secondary School Teacher','Special Education Teacher','Early Childhood Educator','University Lecturer','Professor','Teaching Assistant','Instructional Designer','Curriculum Developer','Educational Consultant','School Counselor','Academic Advisor','Career Counselor','Education Administrator','School Principal','School Administrator','Corporate Trainer','Learning and Development Specialist','Tutor','Private Tutor','Language Teacher','English Language Teacher','Music Teacher','Art Teacher','Science Teacher','Mathematics Teacher','Education Researcher','Assessment Specialist','Admissions Counselor'],
'Psychology & Human Services':['Psychologist','Clinical Psychologist','Counseling Psychologist','School Psychologist','Industrial-Organizational Psychologist','Social Worker','Clinical Social Worker','Case Manager','Community Health Worker','Mental Health Counselor','Rehabilitation Counselor','Marriage and Family Therapist','Behavior Analyst','Applied Behavior Analyst','Substance Abuse Counselor','Youth Counselor','Child Life Specialist','Human Services Specialist','Family Services Specialist','Victim Advocate','Crisis Counselor','Community Organizer','Social Services Manager','Gerontology Specialist','Disability Services Coordinator'],
'Design & Architecture':['Architect','Landscape Architect','Urban Planner','Regional Planner','Interior Designer','Industrial Designer','Product Designer','Graphic Designer','Visual Designer','Brand Designer','Interaction Designer','User Experience Designer','User Interface Designer','Service Designer','Motion Designer','Art Director','Creative Director','Exhibition Designer','Set Designer','Lighting Designer','Fashion Designer','Textile Designer','Jewelry Designer','Furniture Designer','Packaging Designer','Architectural Designer','CAD Designer','3D Artist','3D Modeler','Technical Illustrator','Environmental Designer'],
'Media & Journalism':['Journalist','Reporter','Investigative Journalist','News Editor','Copy Editor','Managing Editor','News Producer','Broadcast Journalist','Radio Presenter','Television Presenter','News Anchor','Photojournalist','Documentary Producer','Documentary Researcher','Video Producer','Film Producer','Podcast Producer','Podcast Host','Scriptwriter','Screenwriter','Editor','Content Editor','Copywriter','Technical Content Writer','Blogger','Author','Publisher','Book Editor','Media Researcher','Fact Checker','Archivist'],
'Marketing & Sales':['Marketing Manager','Digital Marketing Specialist','Content Marketing Specialist','Social Media Manager','Social Media Specialist','Brand Manager','Product Marketing Manager','Growth Marketing Manager','SEO Specialist','Search Marketing Specialist','Email Marketing Specialist','Public Relations Specialist','Publicist','Communications Manager','Corporate Communications Specialist','Market Researcher','Consumer Insights Analyst','Advertising Account Executive','Advertising Manager','Media Buyer','Media Planner','Sales Manager','Sales Representative','Business Development Representative','Account Executive','Sales Engineer','Real Estate Agent','Fundraising Manager','Donor Relations Specialist','Community Manager'],
'Arts & Creative Practice':['Painter','Illustrator','Sculptor','Ceramic Artist','Printmaker','Photographer','Fine Art Photographer','Animator','Character Animator','Storyboard Artist','Concept Artist','Comic Artist','Mural Artist','Calligrapher','Art Conservator','Museum Curator','Gallery Manager','Museum Educator','Musician','Composer','Music Producer','Sound Designer','Audio Engineer','Singer','Actor','Stage Actor','Theatre Director','Choreographer','Dancer','Costume Designer','Makeup Artist','Hair Stylist'],
'Environment & Agriculture':['Agronomist','Agricultural Scientist','Agricultural Inspector','Agricultural Extension Officer','Horticulturist','Viticulturist','Arborist','Forester','Forest Ranger','Conservation Scientist','Conservation Officer','Wildlife Biologist','Wildlife Manager','Park Ranger','Environmental Consultant','Environmental Planner','Environmental Health Specialist','Sustainability Consultant','Sustainability Manager','Climate Policy Analyst','Renewable Energy Consultant','Water Quality Scientist','Fisheries Biologist','Fisheries Manager','Soil Conservationist','Irrigation Specialist','Farm Manager','Agricultural Economist','Animal Scientist','Beekeeper'],
'Public Service & Government':['Civil Servant','Public Administrator','Policy Analyst','Policy Advisor','Legislative Analyst','Legislative Assistant','Diplomat','Foreign Service Officer','Government Relations Specialist','Public Affairs Specialist','City Manager','Urban Policy Analyst','Municipal Planner','Election Administrator','Public Information Officer','Emergency Management Specialist','Emergency Management Director','Public Safety Administrator','Customs Officer','Immigration Officer','Tax Officer','Revenue Officer','Government Auditor','Regulatory Affairs Specialist','Public Procurement Officer','Community Development Officer','Social Policy Analyst','International Development Specialist','Humanitarian Program Officer','Public Program Manager'],
'Skilled Trades & Manufacturing':['Electrician','Plumber','Carpenter','Cabinetmaker','Welder','Machinist','CNC Machinist','Tool and Die Maker','Millwright','Industrial Maintenance Technician','Automotive Technician','Diesel Technician','Aircraft Maintenance Technician','Motorcycle Mechanic','Small Engine Mechanic','HVAC Technician','Refrigeration Technician','Elevator Technician','Boilermaker','Pipefitter','Sheet Metal Worker','Bricklayer','Mason','Roofer','Glazier','Painter and Decorator','Flooring Installer','Locksmith','Blacksmith','Furniture Maker','Jeweler','Watchmaker','Baker','Pastry Chef','Butcher','Textile Machine Operator','Printing Press Operator','Quality Control Technician','Production Technician','Assembly Technician','Manufacturing Technician'],
'Transportation & Aviation':['Pilot','Commercial Airline Pilot','Helicopter Pilot','Flight Instructor','Air Traffic Controller','Flight Dispatcher','Aircraft Loadmaster','Aviation Safety Inspector','Airport Manager','Airport Operations Manager','Airline Operations Manager','Railway Engineer','Train Driver','Railway Conductor','Rail Traffic Controller','Bus Driver','Truck Driver','Delivery Driver','Taxi Driver','Transit Planner','Transportation Planner','Logistics Coordinator','Ship Captain','Merchant Mariner','Deck Officer','Marine Surveyor','Harbor Master','Port Manager','Airline Customer Service Agent','Flight Attendant'],
'Hospitality & Tourism':['Hotel Manager','Front Office Manager','Concierge','Guest Relations Manager','Event Planner','Conference Coordinator','Wedding Planner','Travel Agent','Travel Consultant','Tour Guide','Tour Manager','Tourism Manager','Destination Manager','Resort Manager','Restaurant Manager','Food and Beverage Manager','Sommelier','Chef','Sous Chef','Pastry Chef','Catering Manager','Banquet Manager','Cruise Director','Cruise Ship Staff','Hospitality Revenue Manager','Hotel Revenue Analyst','Reservations Agent','Housekeeping Manager','Spa Manager','Theme Park Manager'],
'Sports & Fitness':['Athletic Coach','Strength and Conditioning Coach','Personal Trainer','Fitness Instructor','Yoga Instructor','Pilates Instructor','Sports Scientist','Sports Analyst','Sports Statistician','Sports Psychologist','Sports Nutritionist','Athletic Trainer','Physiotherapist','Exercise Physiologist','Recreation Coordinator','Sports Manager','Athletics Director','Scouting Analyst','Talent Scout','Sports Agent','Referee','Umpire','Sports Official','Outdoor Adventure Guide','Climbing Instructor','Swimming Coach','Dance Fitness Instructor','Wellness Coach','Performance Coach','Physical Education Teacher'],
'Social Sciences & Policy':['Sociologist','Political Scientist','Anthropologist','Archaeologist','Demographer','Criminologist','Urban Sociologist','International Relations Specialist','Development Economist','Policy Researcher','Public Policy Researcher','Social Researcher','Survey Researcher','Population Scientist','Community Researcher','Political Analyst','Geopolitical Analyst','Research Coordinator','Think Tank Researcher','Program Evaluation Specialist','Monitoring and Evaluation Specialist','Human Rights Researcher','Peace and Conflict Researcher','Migration Researcher','Labor Economist','Social Impact Analyst']
};

const CDNA_DOMAIN_NAMES = Object.keys(CDNA_CAREER_SETS);
const CDNA_CAREER_CATALOG = [];
const seen = new Set();
for (const domain of CDNA_DOMAIN_NAMES) {
  const p = CDNA_DOMAIN_PROFILES[domain];
  for (const name of CDNA_CAREER_SETS[domain]) {
    const key = name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
    if (seen.has(key)) continue;
    seen.add(key);
    CDNA_CAREER_CATALOG.push({
      id:key,name,domain,
      description:`A professional path focused on ${name.toLowerCase()} work within ${domain.toLowerCase()}. The role typically combines domain knowledge, practical judgment and role-specific skills.`,
      traits:{...p.traits}, interests:[...p.interests], workStyles:[...p.workStyles], environments:[...p.environments], motivations:[...p.motivation], skills:[...p.skills], education:p.education,
      relatedCareers:CDNA_CAREER_SETS[domain].filter(x=>x!==name).slice(0,4)
    });
  }
}

if (CDNA_CAREER_CATALOG.length < 500) console.warn('CAREER DNA catalog below 500:', CDNA_CAREER_CATALOG.length);
